# Copyright (c) 2020-2022 Raphael Pothin.
# Licensed under the MIT License.

name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    # Action used to checkout the main branch in the current repository
    #   Community action: https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v3.0.2
      
    - name: Test
      run: |
        Write-Host "========== Without inputs =========="
        gh run list

        Write-Host "========== Correct call =========="
        gh run list -b work/193 -w import-solution-to-dev.yml --json name,headBranch,databaseId,status,conclusion,url
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_WORKFLOW_UPDATE }}