# Copyright (c) 2020 Raphael Pothin.
# Licensed under the MIT License.

name: 0-Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2

      - name: Get Power Apps CLI
        run: |
          $nugetPackage = "Microsoft.PowerApps.CLI"
          $nugetPackageVersion = "1.7.4"
          $outFolder = "pac"
          
          nuget install $nugetPackage -Version $nugetPackageVersion -OutputDirectory $outFolder
          
          $pacNugetFolder = Get-ChildItem $outFolder | Where-Object {$_.Name -match $nugetPackage + "."}
          $pacPath = $pacNugetFolder.FullName + "/tools"
          
          Write-Host "$pacPath"
          
          echo "pacPath=$pacPath" >> $Env:GITHUB_ENV
        shell: pwsh

      - name: Unpack canvas app source files
        run: |
          Get-ChildItem -Path "Solutions/PowerPlatformALMWithGitHub" -Recurse -Filter *.msapp | 
          ForEach-Object {
              $unpackedPath = $_.FullName.Replace(".msapp", "_msapp_src")
              $env:PATH = $env:PATH + ";" + "${{ env.pacPath }}"
              pac canvas unpack --msapp $_.FullName --sources $unpackedPath
              del $_.FullName
          }
        shell: pwsh