name: X-test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout
      with:
        ref: work/153
    - uses: ./.github/actions/get-dataverse-environment-configuration
      name: Test