name: X-test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - uses: ./.github/actions/get-dataverse-environment-configuration
      name: Test
      id: test
    - run: echo ${{ steps.test.outputs.build-environment-domain-name-base }}
      shell: bash