# Copyright (c) 2020 Raphael Pothin.
# Licensed under the MIT License.

name: 0-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Test echo"

          Write-Host "Test write-host"

          Write-Verbose "Test write-verbose"
        shell: powershell

      - name: Test
        run: |
          echo "Test echo"

          Write-Host "Test write-host"

          Write-Verbose "Test write-verbose"
        shell: pwsh