# Copyright (c) 2020 Raphael Pothin.
# Licensed under the MIT License.

name: 0-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          $PSVersionTable.PSVersion
        shell: powershell

      - name: Test
        run: |
          Import-Module Microsoft.Xrm.Data.PowerShell -Force -ArgumentList @{ NonInteractive = $true }

          Import-Module Scripts/Update-ConnectionReferences.ps1 -Force

          $ConnectionReferencesUdpateParams = @{
            TenantId = "${{ secrets.TENANT_ID }}"
            ClientId = "${{ secrets.APPLICATION_ID }}"
            ClientSecret = "${{ secrets.CLIENT_SECRET }}"
            DataverseEnvironmentUrl = "https://bafc-rpo-gh-qa.crm3.dynamics.com/"
            SolutionName = "${{ secrets.TENANT_ID }}"
            SolutionComponentsOwnerEmail = "raphael.pothin@bizappsfrenchcommunity.com"
            ConfigurationFilePath = "Scripts/ConnectionsMapping.json"
          }

          Update-ConnectionReferences @ConnectionReferencesUdpateParams -verbose
        shell: powershell