# Copyright (c) 2020 Raphael Pothin.
# Licensed under the MIT License.

name: 0-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          Install-Module Microsoft.Xrm.Data.PowerShell -Scope CurrentUser -Force

          Import-Module ./Scripts/Enable-CloudFlows.ps1 -Force

          $CloudFlowsActivationParams = @{
            TenantId = "${{ secrets.TENANT_ID }}"
            ClientId = "${{ secrets.APPLICATION_ID }}"
            ClientSecret = "${{ secrets.CLIENT_SECRET }}"
            DataverseEnvironmentUrl = "https://bafc-rpo-gh-qa.crm3.dynamics.com/"
            SolutionName = "PowerPlatformALMWithGitHub"
            SolutionComponentsOwnerEmail = "raphael.pothin@bizappsfrenchcommunity.com"
          }

          Enable-CloudFlows @CloudFlowsActivationParams -verbose
        shell: powershell